### ISSUE TITLE
God's Flesh but it's not worthless this time

### ISSUE THREAD

**Issue by Lonrite** [UnderscoreKilburn/repentance-issues#1764]
enemies should blink a bit before the effect wears off, as a tell for when it'll happen - so you don't have to constantly be anxious thinking if you should use it or no

they should also get stunned for like a second or two before running away in fear - the item would be way better this way

i also don't remember if you're protected against explosive enemies / tears on-death enemies/champions, or enemy spawners in Rep but would be neat

**Comment by Rchardon** [comment]
Fixed in Rep+ !

**Comment by Lonrite** [comment]
it both got a nerf and a buff ( by nerf I mean enemies running away like scared hearts ) - I still don't like it much but at least it's not actively garbage like before
